name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install tccli
        run: pip install tccli
      - name: Check if tccli installed
        run: tccli --version
      - name: Declare some variables
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        run: dotnet publish -o ./target
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ccr.ccs.tencentyun.com/han_test/my-web-app:${{ steps.vars.outputs.sha_short }}
      - name: Qcloud tccli configuration
        run: |
          tccli configure set secretId ${{ secrets.QCLOUD_SECRET_ID }}
          tccli configure set secretKey ${{ secrets.QCLOUD_SECRET_KEY }}
          tccli configure set region ${{ secrets.QCLOUD_REGION }}
          tccli configure set output json
      - name: Construct DeployServiceV2 Arguments
        run: cat /tmp/tem_deploy_service_v2.json | tr "$tag" ${{ steps.vars.outputs.sha_short }} > tem_deploy_service_v2.json
      - name: DeployService in TEM
        run: tccli tem DeployServiceV2 --cli-input-json file:///tmp/tem_deploy_service_v2.json
        
      
